### ISSUE TITLE
Prevent reading/writing empty `FeatureTable`s

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-types#144]
**Current Behavior**
Currently methods like `feature-table filter-samples` can filter out all values in a table, resulting in a successfully created (albeit empty) artifact. This then causes problems in other methods, where they expect to have *some* data in the table. As well, without this centralized check, the burden of checking for data in these tables falls on the plugin developer, which creates some extra work.

**References**
This is a more specific case of https://github.com/qiime2/qiime2/issues/294.

**Comment by thermokarst** [comment]
This came up on [the forum](https://forum.qiime2.org/t/feature-table-filter-samples-removes-taxonomy-from-biom-table/1159).

**Comment by jairideout** [comment]
:+1: for disallowing the reading and writing of empty feature tables in QIIME 2. We took a similar strategy in more recent versions of QIIME 1 and it seems to work well. There's a certain elegance to supporting the "null" case for a data structure, but in practice (like @thermokarst noted) it places burden on plugin developers because every method/visualizer needs to either 1) work correctly with an empty table, or 2) fail gracefully. Either way, this also requires the plugin developer to write unit tests for the empty table border case, which is easy to forget.

**Comment by lizgehret** [comment]
A good solution here would be to add a flag of some sort, like `--allow-empty-table` that is disabled by default, since an empty feature table should _technically_ be allowed, even if it's not useful. Bumping this to our rainy day board, since this could be useful.

**Comment by hagenjp** [comment]
This issue was resolved by [#292](https://github.com/qiime2/q2-feature-table/pull/292)
