### ISSUE TITLE
add JoinedFastqManifestPhred33 as a format for joined reads

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-types#162]

**Comment by ebolyen** [comment]
This seems like it kind of counteracts the distinction between semantic type and format, since there isn't really a difference here between single and joined from a data-structure perspective.

In  my mind we would *want* to share the formats between SingleEnd and JoinedEnd as it means less code, testing, and transformers.

Granted the current naming is probably confusing.

**Comment by gregcaporaso** [comment]
@ebolyen, that makes sense. It's really just the confusing naming that I'm trying to get around.

**Comment by thermokarst** [comment]
What about `SingleOrJoinedFastqManifestPhred33` (coupled with deprecating `SingleEnd`...)?

**Comment by lizgehret** [comment]
This is handled [here](https://github.com/qiime2/q2-types/blob/d297c531d31e312f412675e0ded9344f0afb75fd/q2_types/per_sample_sequences/_type.py#L22), closing as completed.
