### ISSUE TITLE
FeatureData[Taxonomy] mangles SILVA taxonomy a little bit

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-types#165]
**Bug Description**
SILVA taxonomies sometimes include `#`s in their strings.

qiime thinks that `#`s start comments, I think, and rstrips them.

So SILVA gets 37 incorrect taxonomy strings (out of 347,146, so relax). But it should really be fixed.

**Screenshots**
Demonstration:

```
$ qiime tools import --input-path just_hashes.txt --type FeatureData[Taxonomy] --source-format HeaderlessTSVTaxonomyFormat --output-path no-hashes.qza
$ qiime tools export no-hashes.qza --output-dir transmogrified
$ grep -c '#' just_hashes.txt 
37
$ grep -c '#' transmogrified/taxonomy.tsv 
0
```

**References**
Example file [here](https://github.com/qiime2/q2-types/files/1577474/just_hashes.txt).

**Comment by ebolyen** [comment]
[forum x-ref](https://forum.qiime2.org/t/taxa-barplot-plugin-error/3219)

**Comment by ebolyen** [comment]
[forum x-ref](https://forum.qiime2.org/t/feature-classifier-not-enough-values-to-unpack/3551)

**Comment by jprctr** [comment]
I couldn't get this solved, but here are some hints for the next person.

The best approach I found was to drop the `comment` parameter from `read_csv` in `feature_data/_transformer.py` and then filter out lines starting with '#' like so:

```
df = pd.read_csv(filepath, sep='\t', skip_blank_lines=True, header=None, dtype=object)
df = df[~df[0].astype(str).str.startswith('#')].dropna()
```

This results in 3 errors in the tests. You can resolve one by adding:
```
    if df.empty:
        raise pd.io.common.EmptyDataError
```
I haven't been able to resolve the others.

The other option would be to preprocess the file before creating a DataFrame with the constructor instead of read_csv, but this requires altering the way header setting / checking is done, which I have not worked out.

```
def _preprocess(filepath, separator, comment):
    with open(filepath, 'r') as file:
        for line in file:
            if len(line) > 0:
                if not line[0].startswith(comment) and not line.isspace():
                    yield line.replace('\n','').split(separator)

    data = _preprocess(filepath=filepath, separator='\t', comment='#')
    header = None
    if has_header is not None:
        header = next(data)
    df = pd.DataFrame(data, columns=header, dtype=object)
```

Hope this is helpful.

**Comment by BenKaehler** [comment]
Some time before the 2020.8 release, this was fixed. It is no longer a problem, unless it has be reintroduced since 2020.8.
