### ISSUE TITLE
BUG: users can create incomplete SingleLanePerSamplePairedEndFastqDirFmt

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-types#218]
**Bug Description**
A forum user was able to import `SingleLanePerSamplePairedEndFastqDirFmt` data, without the `MANIFEST` or `metadata.yml` files (in their place was `MANIFEST.txt` and `metadata.yml.txt`).

```bash
unzip demux\(1\).qza
Archive:  demux(1).qza
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/checksums.md5
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/metadata.yaml
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/VERSION
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/AEMK01_S39_L001_R1_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/AEMK01_S39_L001_R2_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/AUP03_S47_L001_R1_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/AUP03_S47_L001_R2_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/GCVB01_S38_L001_R1_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/GCVB01_S38_L001_R2_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/GMDM06_S55_L001_R1_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/GMDM06_S55_L001_R2_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/KVRF01_S53_L001_R1_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/KVRF01_S53_L001_R2_001.fastq.gz
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/MANIFEST.txt
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/data/metadata.yml.txt
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/provenance/citations.bib
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/provenance/metadata.yaml
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/provenance/VERSION
  inflating: b622bb88-526a-4b22-a5f7-af6555fd9191/provenance/action/action.yaml
```

**Expected behavior**
An error should've been raised when the user imported this format (which, was incomplete, and had extra files).

**Comments**
1. I am filing this bug here in q2-types, because the current, concrete error is related to `SingleLanePerSamplePairedEndFastqDirFmt`, but, it seems very possible that the root issue is in the framework.

**References**
1. [Original forum thread](https://forum.qiime2.org/t/manifest-does-not-exist-error/10578?u=thermokarst)
2. [User's data (gdrive)](https://drive.google.com/file/d/1zvu8GU3WAkEJJy89zPum1d5I3Y7_X_2O/view?usp=sharing)

**Comment by thermokarst** [comment]
This block in the framework looks promising:

https://github.com/qiime2/qiime2/blob/3e053cba101ace49ba52e16cba0bd6966973b0b3/qiime2/plugin/model/directory_format.py#L102-L105

**Comment by Oddant1** [comment]
@thermokarst the drive link isn't loading for me.

**Comment by thermokarst** [comment]
Thanks @Oddant1 --- looks like the user stopped sharing their data. No worries.

**Comment by Oddant1** [comment]
I took another look at this and it looks like right here in the framework is where the issue is. https://github.com/qiime2/qiime2/blob/81f9bc1e735a1d9c1c852d144b8302ab4c24a3cc/qiime2/plugin/model/directory_format.py#L89-L105 

Specifically on line 93 we regex the pathspec against the actual path which allows any path that is a superset of the pathspec to get through. This explains how "MANIFEST.txt" and "metadata.yml.txt" got through. The path we regex against is the path to the file relative to the root directory of the artifact.

It seems like we might be able to just use `re.fullmatch` instead of `re.match`? Provided the pathspec is the full file path from the artifact's root (so if the file is nested within another directory inside the artifact's data directory that directory is part of its pathspec) I think this should work.

**Comment by thermokarst** [comment]
Awesome! Can you write up a unittest that recreates the case presented here in this issue? It will fail, until we get the fix merged into the framework. Thanks!
